<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Database configuration
$host = 'localhost';
$username = 'root';
$password = '';
$database = 'Bookstore';

// Create connection
$conn = new mysqli($host, $username, $password, $database);

// Check connection
if ($conn->connect_error) {
    echo json_encode([
        'success' => false,
        'error' => 'Connection failed: ' . $conn->connect_error
    ]);
    exit();
}

// 生成自动 ISBN 的函数
function generateISBN() {
    // ISBN 格式: 978-XXXXXX-XX-X
    $prefix = "978";
    $group_publisher = str_pad(mt_rand(100000, 999999), 6, '0', STR_PAD_LEFT);
    $title = str_pad(mt_rand(10, 99), 2, '0', STR_PAD_LEFT);
    
    // 计算校验码
    $isbn_without_check = $prefix . $group_publisher . $title;
    $check_digit = calculateISBN13CheckDigit($isbn_without_check);
    
    return sprintf("%s-%s-%s-%s", $prefix, $group_publisher, $title, $check_digit);
}

function calculateISBN13CheckDigit($isbn12) {
    $sum = 0;
    for ($i = 0; $i < 12; $i++) {
        $digit = (int)$isbn12[$i];
        $sum += ($i % 2 == 0) ? $digit : $digit * 3;
    }
    return (10 - ($sum % 10)) % 10;
}

function isISBNUnique($conn, $isbn) {
    $stmt = $conn->prepare("SELECT COUNT(*) as count FROM books WHERE isbn = ?");
    $stmt->bind_param("s", $isbn);
    $stmt->execute();
    $result = $stmt->get_result();
    $row = $result->fetch_assoc();
    $stmt->close();
    return $row['count'] == 0;
}

// Get JSON input
$input = json_decode(file_get_contents('php://input'), true);

// 处理ISBN逻辑
$isbn = '';
$isAutoGenerated = false;

if (!empty($input['id'])) {
    // 更新书籍 - 使用传入的ISBN或保持原样
    $isbn = !empty($input['isbn']) ? $input['isbn'] : '';
} else {
    // 新增书籍 - 自动生成ISBN
    $isAutoGenerated = true;
    
    // 如果前端提供了ISBN（比如从表单），使用它
    if (!empty($input['isbn']) && trim($input['isbn']) !== '') {
        $isbn = trim($input['isbn']);
    } else {
        // 自动生成唯一ISBN
        $max_attempts = 5;
        for ($i = 0; $i < $max_attempts; $i++) {
            $generated_isbn = generateISBN();
            if (isISBNUnique($conn, $generated_isbn)) {
                $isbn = $generated_isbn;
                break;
            }
        }
        
        // 后备方案
        if (empty($isbn)) {
            $timestamp = substr(time(), -6);
            $random = mt_rand(1000, 9999);
            $base_isbn = "978" . $timestamp . str_pad($random % 100, 2, '0', STR_PAD_LEFT);
            $check_digit = calculateISBN13CheckDigit($base_isbn);
            $isbn = "978-" . $timestamp . "-" . str_pad($random % 100, 2, '0', STR_PAD_LEFT) . "-" . $check_digit;
        }
    }
}

// Check if it's an update or insert
if (!empty($input['id'])) {
    // Update existing book
    $sql = "UPDATE books SET 
            title = ?, 
            author = ?, 
            category_id = ?, 
            price = ?, 
            stock_quantity = ?, 
            isbn = ?, 
            description = ?, 
            publisher = ?, 
            publish_date = ?,
            updated_at = CURRENT_TIMESTAMP
            WHERE book_id = ?";
    
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("ssidsssssi", 
        $input['title'],
        $input['author'],
        $input['category_id'],
        $input['price'],
        $input['stock_quantity'],
        $isbn,
        $input['description'],
        $input['publisher'],
        $input['publish_date'],
        $input['id']
    );
} else {
    // Insert new book
    $sql = "INSERT INTO books (title, author, category_id, price, stock_quantity, isbn, description, publisher, publish_date) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
    
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("ssidsssss", 
        $input['title'],
        $input['author'],
        $input['category_id'],
        $input['price'],
        $input['stock_quantity'],
        $isbn,
        $input['description'],
        $input['publisher'],
        $input['publish_date']
    );
}

if ($stmt->execute()) {
    $response = [
        'success' => true,
        'message' => !empty($input['id']) ? 'Book updated successfully' : 'Book added successfully'
    ];
    
    if ($isAutoGenerated) {
        $response['generated_isbn'] = $isbn;
        $response['is_auto_generated'] = true;
    }
    
    echo json_encode($response);
} else {
    echo json_encode([
        'success' => false,
        'error' => 'Error saving book: ' . $stmt->error
    ]);
}

$stmt->close();
$conn->close();
?>